server:
  port: 8888

spring:
  application:
    name: lizard-data-admin-backend
  datasource:
    name: DataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://lizard-mysql-server:3306/lizard_data?charset=utf8mb4&useSSL=false
    username: root
    password: ${DATA_MYSQL_PASSWORD}

    hikari:
      maximum-pool-size: 20
      minimum-idle: 3



crypto:
  key: ${CRYPTO_KEY}

